networks:
  shared_network:
    driver: bridge

services:
  webserver:
    container_name: "webserver_${APP_NAME}"
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${WEBSERVICE_PORT}:80'
    networks:
      - shared_network

  php-fpm:
      build: 'docker/php-fpm'
      container_name: "phpserver_${APP_NAME}"
      working_dir: /app
      volumes:
          - '.:/app'
          - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
      networks:
        - shared_network